### ISSUE TITLE
2nd encoder connection

### ISSUE THREAD

**Issue by shiftux** [askuric/Arduino-FOC-reaction-wheel-inverted-pendulum#1]
hello
first off, thanks for the amazing documentation on your cool project!! - great work!
looking to build something similar...
there is 1 thing i don't understand in your setup: the foc-shield, as i understand it, does only allow 1 encoder to be connected to it. you obviously need 2. now i know the shields could be stackable, but you don't seem to stack them... 
how did you solve that? - repurposing free pins? is that then still compatible with the foc library?
thanks!

**Comment by askuric** [comment]
Hey @shiftux 

Yes, the connector for encoder is there more for convenience reasons really. And it provides you a way to use the integrated pull-ups if you need ones. But most of the common encoders do not need any and you can just plug them directly to any digital pin. 

So you can really do the same thing by plugging encoder ground and 5V to Arduino ground and 5v,  And then the a,b and z to the any free Arduino digital pin.  :D

**Comment by shiftux** [comment]
ok, i figured, thanks! :)
